version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "tv_releases_development"
    ports:
      - "5432:5432"

  web:
    build: .
    command: ./bin/docker-entrypoint ./bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/rails
      - node_modules:/rails/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/tv_releases_development"
      RAILS_ENV: development
      NODE_ENV: development
    depends_on:
      - db

volumes:
  postgres-data:
  node_modules: 