version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "tv_releases_development"
    ports:
      - "5432:5432"

  web:
    build: .
    command: ./bin/docker-entrypoint ./bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/rails
      - node_modules:/rails/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/tv_releases_development"
      RAILS_ENV: development
      NODE_ENV: development
    depends_on:
      - db
  crawler:
    image: unclecode/crawl4ai:0.6.0-r2
    ports:
      - "11235:11235"
    env_file:
      - .llm.env
    environment:
      - DEFAULT_LLM_PROVIDER=ollama/gemma3:27b-it-q4_K_M
      - OLLAMA_API_KEY=Basic a29sbzpPY2VhbmFfMTk3MA==
      - OLLAMA_API_BASE=https://ollama-1.koloit.net/4
      - LITELLM_API_BASE=https://ollama-1.koloit.net/4
      - LITELLM_API_KEY=
      - LITELLM_DEBUG=true
      - LITELLM_VERBOSE=true
      - PYTHONUNBUFFERED=1
    volumes:
      - ./crawl4ai.config.yml:/app/config.yml:ro
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres-data:
  node_modules: 